# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
