# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170518_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
